server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ramin2004
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: liquibase/changelog-master.yml
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: aliyevramin2019@gmail.com
#    password: aachubybpccvjrjs
#    protocol: smtp
#    tls: true
#    properties.mail.smtp:
#      auth: true
#      starttls.enable: true
#      ssl.trust: smtp.gmail.com


